name : short_fallen_kingdom
authors: [Asbyx, TheChi2000]
version: 0.2
description: Fallen Kingdom Plugin
api-version: 1.16
main: ch.thechi2000asbyx.short_fallen_kingdom.Main
commands:
  allowTntBow:
    description: allow the TNT bow to be used
    permission: op

  allowTomb:
    description: allow the tomb (chest appears on deathOfPlayer) to be used
    permission: op

  game:
    startGame:
      description: Start the game ! May the odds be with you
      permission: op

    getGameParameters:
      description: Return all current game parameters

    stopGame:
      description: Stop the game.
      permission: op

  middleChest:
    description: Creates the middle chest and display its position to everyone

  fkteam:
    description: Execute action on teams
    usage: /<command> <action> <args>
#[create|addPlayer|setBaseLocation|getBaseLocation|teams|players]



#name : tomb
#author: Asbyx
#version: 0.1
#description: Put a tomb at the death location of the player
#api-version: 1.16
#main: ch.Asbyx.tomb.Main


#name : firstPlugin
#author: Asbyx
#version: 0.2
#description: Premier plugin !
#api-version: 1.16
#main: ch.Asbyx.firstPlugin.Main
#commands:
#  coucou:
#    description: Send "Salut" in the global chat
#    aliases: [cc, slt]
#
#  showCoordinates:
#    description: Send the player's coordinates in the global chat, or just to args[0] (name of the player)
#    aliases: [sc]
#
#  startGame:
#    description: Send every player location every args[0] seconds
#
#  stopGame:
#    description: stop every scheduler