name : firstPlugin
author: Asbyx
version: 0.1
description: Premier plugin !
main: fr.Asbyx.firstPlugin.Main
commands:
  coucou:
    description: Send "Salut" in the global chat
    aliases: [cc, slt]

  showCoordinates:
    description: Send the player's coordinates in the global chat
    aliases: [sc]
