name : LeGrandGroupePlugin
authors: [Asbyx, TheChi2000]
version: 0.3
description: Grand Plugin Plugin
api-version: 1.17
main: ch.grandgroupe.common.Main
commands:
  worlds:
    description: test

  rules:
    tntBow:
      description: allow the TNT bow to be used
      permission: op
    tomb:
      description: allow the tomb (chest appears on deathOfPlayer) to be used
      permission: op
    nudeBow:
      description: allow the nude bow to be used
      permission: op
    harvester: allow the harvester to be used

  fk:
    game:
      startGame:
        description: Start the game ! May the odds be with you
        permission: op
      getGameParameters:
        description: Return all current game parameters
      stopGame:
        description: Stop the game.
        permission: op
      middleChest:
        description: Creates the middle chest and display its position to everyone

    teams:
      description: Execute action on teams
      usage: /<command> <action> <args>

  speedrun:
    start:
      description: Start the game
      permission: op
    stop:
      description: Stop the game
      permission: op

  training:
    start:
      description: Start the training

    stop:
      description: Stop the training